services:
  - type: web
    name: antimemer-api
    env: docker
    region: oregon # optional (defaults to oregon)
    plan: free # optional (defaults to starter)
    branch: main # optional (uses repo default)
    numInstances: 1 # optional (defaults to 1)
    dockerfilePath: ./apps/api/Dockerfile
    dockerContext: .
    pullRequestPreviewsEnabled: false # optional
    autoDeploy: true # optional
    healthCheckPath: /healthz
    envVars:
      - key: JWT_ACCESS_SECRET
        value: nestjsPrismaAccessSecret
      - key: JWT_REFRESH_SECRET
        value: nestjsPrismaRefreshSecret
      - key: PORT
        value: 4000
      - key: DATABASE_URL
        fromDatabase:
          name: antimemer-db
          property: connectionString
  - type: web
    name: antimemer-web
    env: docker
    region: oregon # optional (defaults to oregon)
    plan: free # optional (defaults to starter)
    branch: main # optional (uses repo default)
    numInstances: 1 # optional (defaults to 1)
    dockerfilePath: ./apps/web/Dockerfile
    dockerContext: .
    pullRequestPreviewsEnabled: false # optional
    autoDeploy: true # optional
    envVars:
      - key: API_URL
        fromService:
          name: antimemer-api
          type: web
          property: hostport
      - key: APP_ENV
        value: production
databases:
  - name: antimemer-db
    databaseName: antimemer_db # optional (Render may add a suffix)
    user: antimemer_db_user # optional
    plan: starter
