services:
  - type: web
    name: api
    env: docker
    region: oregon # optional (defaults to oregon)
    plan: free # optional (defaults to starter)
    branch: main # optional (uses repo default)
    numInstances: 1 # optional (defaults to 1)
    dockerfilePath: ./apps/api/Dockerfile
    dockerContext: .
    pullRequestPreviewsEnabled: false # optional
    autoDeploy: true # optional
    healthCheckPath: /.well-known/apollo/server-health
    envVars:
      - key: NODE_ENV
        value: production
      - key: WEB_HOSTPORT
        fromService:
          name: web
          type: web
          property: hostport
      - key: JWT_ACCESS_SECRET
        value: nestjsPrismaAccessSecret
      - key: JWT_REFRESH_SECRET
        value: nestjsPrismaRefreshSecret
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        fromDatabase:
          name: db
          property: connectionString
  - type: web
    name: web
    env: docker
    region: oregon # optional (defaults to oregon)
    plan: free # optional (defaults to starter)
    branch: main # optional (uses repo default)
    numInstances: 1 # optional (defaults to 1)
    dockerfilePath: ./apps/web/Dockerfile
    dockerContext: .
    pullRequestPreviewsEnabled: false # optional
    autoDeploy: true # optional
    envVars:
      - key: API_URL
        fromService:
          name: api
          type: web
          property: hostport
      - key: APP_ENV
        value: production
databases:
  - name: db
    plan: free
    region: oregon
    postgresMajorVersion: 14
